#!/bin/sh

ask-link ~/.otcova-setup/config/tmux.conf ~/.tmux.conf
git-install 'https://github.com/tmux-plugins/tpm' ~/.tmux/plugins/tpm

if ! command -v tmux >/dev/null; then
  mkdir -p ~/.otcova-setup/.bin
  wget -qO ~/.otcova-setup/.bin/tmux https://github.com/kiyoon/tmux-appimage/releases/download/3.5a/tmux.appimage
  chmod +x ~/.otcova-setup/.bin/tmux
fi
