#!/bin/sh

help=''

if [ "$(tput colors)" -ge 8 ]; then
  reset='\e[0m'
  green='\e[1;32m'
  blue='\e[1;34m'
fi

header() { help="$help\n$blue$1$reset\n"; }
shortcut() { help="$help$1$green $2$reset\n"; }

header "Revert"
shortcut "git revert <commit>  " "Create a new commit reverting <commit>"
shortcut "git reset HEAD~1     " "Deletes most recent commit"

header "Change"
shortcut "git commit --amend --reset-author --no-edit" "Change most recent commit author"
shortcut "git commit --amend --message '<msg>'       " "Change most recent commit message"

printf "$help\n" | less -r
